trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Install python'

- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install selenium
  displayName: 'Install selenium'

- script: |
    wget http://security.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.4_amd64.deb
    sudo dpkg -i apt_1.4_amd64.deb
    apt-get install procps 
    free -h
  displayName: 'Check memory'

- script: python3 google-serach-lambdatest.py
  displayName: 'Run tests'

