trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Install python'

- script: python3 -m pip3 install --upgrade pip3 setuptools wheel
  displayName: 'Install tools'

- script: pip3 install selenium
  displayName: 'Install selenium'

- script: for i in {1..100}; do python3 google-serach-lambdatest.py  & done
  displayName: 'Run tests'