trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Install python'

- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install selenium
  displayName: 'Install selenium'

- script: | 
    for i in {1..100}; do python3 google-serach-lambdatest.py  & done
  displayName: 'Run tests'

steps:
  - task: Delay@1
    inputs:
      delayForMinutes: '5'